name: API Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "API_KEY=${{ vars.API_KEY }}" >> .env
          echo "USER_ID=${{ vars.USER_ID }}" >> .env
          echo "AUDIT_NAME=${{ vars.AUDIT_NAME }}" >> .env

      - name: Run tests
        run: npm test
